name: ogp_data_extract
description: This is a new package project for extracting ogp data on web pages.This library allows you to retrieve metadata items defined in "The Open Graph protocol".In addition, Facebook and Twitter metadata are supported.
version: 0.1.3
homepage: https://github.com/KINTO-JP/ogp_data_extract

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.0.0
  string_validator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
